### ISSUE TITLE
Cannot delete component from page in CQ

### ISSUE THREAD

**Issue by jstomasi** [coresecure/Adobe-CQ5-Brightcove-Connector#1]
I installed the component on CQ and completed integration instructions.  Everything seems to be functioning properly.  The only problem is, I am unable to delete the componenet from a page, once added.  If I move the component to a different location (paragraph component location) I can delete it.  The other issue is, I had to add two <BR/>'s at the bottom of the component to be able to edit it once a video is added, as flash conflicts with the Authoring environment.

**Comment by yan-kisen** [comment]
authoring has been updated to use editbars rather than rollovers
