### ISSUE TITLE
Desire for author to define alignment

### ISSUE THREAD

**Issue by JEBailey** [coresecure/Adobe-CQ5-Brightcove-Connector#10]
I've already implemented a code fix.

Currently the alignment for the player is defined in the page definition. This means that for each player we could potentially have three pages to represent each configuration. Where as whether alignment is needed or not is really an authoring decision at the page level.

I implemented a minimal impact solution, where an author can define alignment *if* the player page alignment is not defined.

*if* the player page has a defined alignment, that will take precedence.

If desired I can reverse this, so that author overrides the player page definition.

**Comment by yan-kisen** [comment]
This feature was included in the 4.1.0 update.
