### ISSUE TITLE
Videos not loading in 4.1

### ISSUE THREAD

**Issue by jakeScorpio** [coresecure/Adobe-CQ5-Brightcove-Connector#15]
We've set up the Brightcove connector version 4.1 in AEM 6.1 and can see our library of videos, however the videos won't work in preview nor in the HTML5 video component. Please advise?

**Comment by balajisetty** [comment]
Facing same set of issues. Also not able to edit the video from console.

**Comment by yan-kisen** [comment]
Can you provide additional information?

Do you see errors in your browser console?

**Comment by balajisetty** [comment]
Yes when i try to edit, i get following error in console.

Uncaught TypeError: modDate.getMonth is not a function
extMetaEdit	@	clientlibs.js:2356
onclick	        @	admin:309

On Video playing part, player opens and freezes. There are no errors on console.

**Comment by balajisetty** [comment]
Got the issue with "Edit dialog". Wondering if any one has tried getting preview fixed. Looks like we are asking previewPlayer to play. Is this some thing that needs to be configured explicitly?

**Comment by balajisetty** [comment]
I got video preview and edit functionality fixed. Those are very minor fixes. Need to check if i have permission to check in the code.

**Comment by yan-kisen** [comment]
Thanks @balajisetty 

You're changed have been merged into master, and the version has been bumped to 4.1.1-SNAPSHOT
