### ISSUE TITLE
Default Administrators group is not correct for AEM 6.2

### ISSUE THREAD

**Issue by puradawid** [coresecure/Adobe-CQ5-Brightcove-Connector#17]
Brightcove configuration has incorrect default group - `administrators`. Because admin account is not in administrators group by default probably it should be `authors` or leave blank

**Comment by alessandro-bonfatti** [comment]
The default configuration must be used only as a reference. Groups should be defined on a case by case scenario.
The default value is now empty.

**Comment by njariwala6177** [comment]
We are getting the same issue with "administrators" and "authors" group. It doesn't work when we leave it blank.

Any thoughts???

**Comment by rajeevyadav2** [comment]
Any update on this issue? I am also facing same issue in AEM 6.3

**Comment by alessandro-bonfatti** [comment]
Like I said before, the default configuration must be used only as a reference. Groups should be defined on a case by case scenario.
The default value is now empty and you need to populate it with the correct group(s) you are going to be using in your environment.
