### ISSUE TITLE
Using deprecated API?

### ISSUE THREAD

**Issue by funkman** [coresecure/Adobe-CQ5-Brightcove-Connector#30]
Is this using the deprecated media API? Are there any plans to use the appropriate replacements?

https://docs.brightcove.com/en/video-cloud/media/references/reference.html

If this is using the deprecated media API - This component will fail at the end of the year (December 31, 2017)

**Comment by alessandro-bonfatti** [comment]
Yes, we are currently working on the new version of the connector.
