### ISSUE TITLE
Brightcove Shared clientlib being loaded on content pages

### ISSUE THREAD

**Issue by mahicks11** [coresecure/Adobe-CQ5-Brightcove-Connector#6]
The shared clientlib for brightcove (/etc/designs/cs/brightcove/shared.css) is part of the OOTB 'cq.shared' clientlib which gets loaded on pages. Can they be decoupled so brightcove's shared clientlib doesn't get loaded on regular content pages?

**Comment by yan-kisen** [comment]
There doesn't seem to be a more effective way of targeting the welcome screen of the classic UI, (which does not use clientlibs) other than overlaying "/libs/cq/core/content/welcome"

Closing unless someone can suggest an alternative to combining with "cq.shared"
